### PR TITLE
build: upgrade GeoTools dependency to 29.2

### PR DESCRIPTION
**Pull request by florianesser**
ING-4041

### CODE REVIEW

**Review by emanuelaepure10 — APPROVED** [review]
Works perfectly for me!

**Comment by florianesser** [comment]
If I understand the GitHub Actions output correctly, it complains about vulnerabilities found in the libraries. @stempler Would you say that this PR can be merged anyway or is there anything that I can/should do first?

**Comment by stempler** [comment]
@florianesser I would see as the condition for merging that this works in hale studio, so that whoever does the next update to the target platform can build on it without needing to resolve issues first that stem from the Geotools changes.
Does it work in hale studio (build+tests) with the changes? If yes would I would propose to directly follow-up with the integration in hale studio.

**Comment by florianesser** [comment]
Ah, didn't think about that, thanks for the clarification, @stempler. In that case this PR doesn't make sense IMO and the bump of the GeoTools version should be done as part of ING-4083 together will all other changes to the platform that might be necessary.

**Comment by stempler** [comment]
Yes, though it can also be used as a starting point for the implementation ticket and e.g. remain open but as draft.

**Pull request closed without merging**
