### PR TITLE
build: update bundled resources and add XPlanGML 6.0 schema preset

### PR DESCRIPTION
**Pull request by kapil-agnihotri**
ING-3369

### CODE REVIEW

**Review by florianesser — APPROVED** [review]
LGTM

**Comment by thorsten-reitz** [comment]
Could it be that the additional comment that 5.4 should also be added got lost somewhere in translation to the ING ticket :)?

https://github.com/halestudio/hale/issues/966#issuecomment-1140310012

**Comment by kapil-agnihotri** [comment]
> Could it be that the additional comment that 5.4 should also be added got lost somewhere in translation to the ING ticket :)?

Thanks a lot @thorsten-reitz for the feedback. Yes, indeed `5.4` got lost. I will update the PR and [hale-build-support](https://gitlab.wetransform.to/hale/hale-build-support) too.

**Comment by kapil-agnihotri** [comment]
I have updated the PR with `5.4` schema preset as well. Please let me know your feedback.

**Pull request merged**
